# Generated by Django 3.0.6 on 2020-08-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cvlist_cvtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvlist',
            name='pageTitle',
            field=models.TextField(default='New Page'),
        ),
        migrations.AddField(
            model_name='cvtext',
            name='pageTitle',
            field=models.TextField(default='New Page'),
        ),
    ]
